#ifndef __SVMainFrame__
#define __SVMainFrame__

/**
@file
Subclass of MainFrame, which is generated by wxFormBuilder.
*/

#include "gui.h"
#include <wx/config.h>
#include <wx/msgdlg.h>
#include <iostream>
#include "base64.h"
#include <wx/socket.h>
#include <wx/url.h>
#include <wx/wfstream.h>
#include <wx/socket.h>
#include "sievecommand.h"
#include <string>
#include <wx/fileconf.h>


/** Implementing MainFrame */
class SVMainFrame : public MainFrame
{
protected:
	// Handlers for MainFrame events.

	void OnClickEnDisBtn( wxCommandEvent& event );

	void OnCancelButtonClickSetting( wxCommandEvent& event );
	void OnSaveButtonClickSetting( wxCommandEvent& event );
        void OnSaveButtonClickScript( wxCommandEvent& event );
	void OnCancelButtonClickScript( wxCommandEvent& event );
	void OnClickCloseBtn( wxCommandEvent& event );

        void OnSocketEvent( wxSocketEvent& event );

public:
	/** Constructor */
	SVMainFrame( wxWindow* parent );
        int LoginSV();

        /** Destructor */
	~SVMainFrame();
private:
        void ReadSock();
        void WriteSock(wxString senddata);
        wxSocketClient *m_sock;
        bool    m_busy;
        bool  LoginOK;
        wxString recvstr;


        DECLARE_EVENT_TABLE()

};
// IDs for the controls and the menu commands
enum
{
      SOCKET_ID
};
#endif // __SVMainFrame__
